// Generated by gencpp from file nmpc_robo/otimizador.msg
// DO NOT EDIT!


#ifndef NMPC_ROBO_MESSAGE_OTIMIZADOR_H
#define NMPC_ROBO_MESSAGE_OTIMIZADOR_H

#include <ros/service_traits.h>


#include <otimizadorRequest.h>
#include <otimizadorResponse.h>


namespace nmpc_robo
{

struct otimizador
{

typedef otimizadorRequest Request;
typedef otimizadorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct otimizador
} // namespace nmpc_robo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nmpc_robo::otimizador > {
  static const char* value()
  {
    return "5b0d5cfd74652255dd251ac777e7f218";
  }

  static const char* value(const ::nmpc_robo::otimizador&) { return value(); }
};

template<>
struct DataType< ::nmpc_robo::otimizador > {
  static const char* value()
  {
    return "nmpc_robo/otimizador";
  }

  static const char* value(const ::nmpc_robo::otimizador&) { return value(); }
};


// service_traits::MD5Sum< ::nmpc_robo::otimizadorRequest> should match
// service_traits::MD5Sum< ::nmpc_robo::otimizador >
template<>
struct MD5Sum< ::nmpc_robo::otimizadorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nmpc_robo::otimizador >::value();
  }
  static const char* value(const ::nmpc_robo::otimizadorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nmpc_robo::otimizadorRequest> should match
// service_traits::DataType< ::nmpc_robo::otimizador >
template<>
struct DataType< ::nmpc_robo::otimizadorRequest>
{
  static const char* value()
  {
    return DataType< ::nmpc_robo::otimizador >::value();
  }
  static const char* value(const ::nmpc_robo::otimizadorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nmpc_robo::otimizadorResponse> should match
// service_traits::MD5Sum< ::nmpc_robo::otimizador >
template<>
struct MD5Sum< ::nmpc_robo::otimizadorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nmpc_robo::otimizador >::value();
  }
  static const char* value(const ::nmpc_robo::otimizadorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nmpc_robo::otimizadorResponse> should match
// service_traits::DataType< ::nmpc_robo::otimizador >
template<>
struct DataType< ::nmpc_robo::otimizadorResponse>
{
  static const char* value()
  {
    return DataType< ::nmpc_robo::otimizador >::value();
  }
  static const char* value(const ::nmpc_robo::otimizadorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NMPC_ROBO_MESSAGE_OTIMIZADOR_H
